### ISSUE TITLE
限界まで”縮小”をクリックすると文字が重なる問題

### ISSUE THREAD

**Issue by kitokun** [norihitoishida/adjust-posts#13]
![2021-08-15 (2)](https://user-images.githubusercontent.com/43565799/129456152-e58c47f5-4a3a-4791-8d3a-0b21ee8fc80e.png)

**Comment by yousukeayada** [comment]
こちら対応しました

**Comment by norihitoishida** [comment]
報告＆対応ありがとうございます！助かります！
