### ISSUE TITLE
「改行数を固定する」のUX改善

### ISSUE THREAD

**Issue by norihitoishida** [norihitoishida/adjust-posts#16]
お便りに空行が含まれている場合、「行末に「。」を追加する」と「改行数を固定する(空白1行)」をオフにすることでキチンと表示できるんですが、UXが良くないので改善します

**↓良くない例**

![Screenshot from 2021-08-15 12-49-41](https://user-images.githubusercontent.com/46351322/129466470-220c7974-f1c4-4657-9efd-a512669d160a.png)

**↓良い例**

![Screenshot from 2021-08-15 12-53-43](https://user-images.githubusercontent.com/46351322/129466511-a7ad7a7f-0e64-4a34-bee5-33584c445a66.png)

**Comment by radiopunch** [comment]
こちらの件ですが、置換処理の順序を変えて、"改行数を固定する処理"を"行末に「。」を追加する”処理の前に持っていくことで解決できそうです。

**Comment by radiopunch** [comment]
こちら手が空いてるので対応しています。

**Comment by radiopunch** [comment]
改行のみの行には句点を追加しないように修正したプルリクを送りました。
これで良い例に示されているような動作になったかと思います。

**Comment by norihitoishida** [comment]
ありがとうございます！ #18
