### ISSUE TITLE
前回のお便り配信を見返して思ったこと

### ISSUE THREAD

**Issue by radiopunch** [norihitoishida/adjust-posts#24]
BSS配信を見返して思ったことです。
あくまで感想なので、他の方のご意見も伺いたいです。

- フォームの幅が広すぎてレイアウトに苦労していたような気がするので幅調整の機能をつけるべき？
- 行間が広すぎたようなので(行間0以上に狭くしようとクリックしていた)、2連改行をデフォルトOFFにして行間値をデフォルト0.5に設定するべき？

**Comment by norihitoishida** [comment]
@radiopunch 

### フォームの幅調整
- ブラウザ自体を狭くすれば良いので恐らく不要ではないかと思います

### 2連改行をデフォルトOFFにして行間値をデフォルト0.5に設定
- 同意します。実装しておきます。

**Comment by norihitoishida** [comment]
@radiopunch 
mainにpushしました(デフォルト値は自分の好みで0.7にしときました)。
UbuntuのFirefox、スマホ(Android)のChromeとKiwiだとうまくいくんですが、UbuntuのChromeだと原因不明の改行が入ってしまいます…とりあえずの対策ですが行間値をマイナスに設定できるようにしておきました。
もし原因や解決策をご存知でしたら教えて下さい…

↓UbuntuのChrome
![FuckChrome](https://user-images.githubusercontent.com/46351322/129735689-995ba258-beaa-4200-86f1-1d3fb37a8e5e.png)

**Comment by norihitoishida** [comment]
今見たら治ってました。マジで何なんだ…
